backend: Add scoped-tls as a dev-dependency
Since aa8607e moved scoped-tls to an optional dependency,
`cargo test -p wayland-backend` fails to build since neither the
client_system nor server_system features are enabled:

    error[E0432]: unresolved import `scoped_tls`
      --> wayland-backend/src/sys/client_impl/mod.rs:26:5
       |
    26 | use scoped_tls::scoped_thread_local;
       |     ^^^^^^^^^^ use of undeclared crate or module `scoped_tls`

    error[E0432]: unresolved import `scoped_tls`
      --> wayland-backend/src/sys/server_impl/mod.rs:20:5
       |
    20 | use scoped_tls::scoped_thread_local;
       |     ^^^^^^^^^^ use of undeclared crate or module `scoped_tls`

    error[E0425]: cannot find value `BACKEND` in this scope
       --> wayland-backend/src/sys/client_impl/mod.rs:378:19
        |
    378 |         let ret = BACKEND.set(&backend, || unsafe {
        |                   ^^^^^^^ help: a local variable with a similar name exists: `backend`

There is code gated with `#[cfg(any(test, feature = "..._system"))]`
which therefore requires scoped-tls during test.